## conv1d

In [2]:
# input shape: (N, Cin, Lin)
# filter shape: (out_channerls, in_channles/group, kW)
# output shape: (N, Cout=out_channels, Lout)

In [5]:
import torch

In [6]:
inputs = torch.ones(5, 16, 50)

In [8]:
filters = torch.ones(2, 16, 1)

In [10]:
import torch.nn.functional as F

In [12]:
F.conv1d(inputs, filters).shape

torch.Size([5, 2, 50])

In [13]:
inputs = torch.ones(2, 3, 4)

In [20]:
filters = torch.ones(1, 3, 3)

In [21]:
F.conv1d(inputs, filters)

tensor([[[9., 9.]],

        [[9., 9.]]])

## conv2d

In [22]:
# input shape: (N, Cin, Hin, Win)
# filter shape: (out_channerls, in_channles/group, kH, kW)
# output shape: (N, Cout, Hout, Wout)

In [24]:
inputs = torch.randn(5, 3, 28, 28)

In [25]:
filters = torch.randn(2, 3, 2, 2)

In [26]:
F.conv2d(inputs, filters).shape

torch.Size([5, 2, 27, 27])

In [27]:
inputs = torch.ones(5, 3, 28, 28)

In [28]:
filters = torch.ones(2, 3, 2, 2)

In [29]:
F.conv2d(inputs, filters)

tensor([[[[12., 12., 12.,  ..., 12., 12., 12.],
          [12., 12., 12.,  ..., 12., 12., 12.],
          [12., 12., 12.,  ..., 12., 12., 12.],
          ...,
          [12., 12., 12.,  ..., 12., 12., 12.],
          [12., 12., 12.,  ..., 12., 12., 12.],
          [12., 12., 12.,  ..., 12., 12., 12.]],

         [[12., 12., 12.,  ..., 12., 12., 12.],
          [12., 12., 12.,  ..., 12., 12., 12.],
          [12., 12., 12.,  ..., 12., 12., 12.],
          ...,
          [12., 12., 12.,  ..., 12., 12., 12.],
          [12., 12., 12.,  ..., 12., 12., 12.],
          [12., 12., 12.,  ..., 12., 12., 12.]]],


        [[[12., 12., 12.,  ..., 12., 12., 12.],
          [12., 12., 12.,  ..., 12., 12., 12.],
          [12., 12., 12.,  ..., 12., 12., 12.],
          ...,
          [12., 12., 12.,  ..., 12., 12., 12.],
          [12., 12., 12.,  ..., 12., 12., 12.],
          [12., 12., 12.,  ..., 12., 12., 12.]],

         [[12., 12., 12.,  ..., 12., 12., 12.],
          [12., 12., 12.,  ..., 12.

## conv3d

In [30]:
# input shape: (N, Cin, Din, Hin, Win)
# filter shape: (out_channerls, in_channles/group, kD, kH, kW)
# output shape: (N, Cout, Dout, Hout, Wout)

In [31]:
inputs = torch.randn(5, 3, 28, 28, 28)

In [32]:
filters = torch.randn(2, 3, 2,2, 2)

In [34]:
F.conv3d(inputs, filters).shape

torch.Size([5, 2, 27, 27, 27])

In [35]:
inputs = torch.ones(5, 3, 28, 28, 28)

In [36]:
filters = torch.ones(2, 3, 2,2, 2)

In [37]:
F.conv3d(inputs, filters)

tensor([[[[[24., 24., 24.,  ..., 24., 24., 24.],
           [24., 24., 24.,  ..., 24., 24., 24.],
           [24., 24., 24.,  ..., 24., 24., 24.],
           ...,
           [24., 24., 24.,  ..., 24., 24., 24.],
           [24., 24., 24.,  ..., 24., 24., 24.],
           [24., 24., 24.,  ..., 24., 24., 24.]],

          [[24., 24., 24.,  ..., 24., 24., 24.],
           [24., 24., 24.,  ..., 24., 24., 24.],
           [24., 24., 24.,  ..., 24., 24., 24.],
           ...,
           [24., 24., 24.,  ..., 24., 24., 24.],
           [24., 24., 24.,  ..., 24., 24., 24.],
           [24., 24., 24.,  ..., 24., 24., 24.]],

          [[24., 24., 24.,  ..., 24., 24., 24.],
           [24., 24., 24.,  ..., 24., 24., 24.],
           [24., 24., 24.,  ..., 24., 24., 24.],
           ...,
           [24., 24., 24.,  ..., 24., 24., 24.],
           [24., 24., 24.,  ..., 24., 24., 24.],
           [24., 24., 24.,  ..., 24., 24., 24.]],

          ...,

          [[24., 24., 24.,  ..., 24., 24., 24.],

## nn.conv1d vs F.conv1d

In [55]:
# nn.Conv1d的filter是随机初始化的

In [39]:
import torch.nn as nn

In [42]:
nn.Conv2d(2, 3, 2, 2)

Conv2d(2, 3, kernel_size=(2, 2), stride=(2, 2))

In [47]:
nn.Conv2d?

In [45]:
f = nn.Conv2d(out_channels=2, in_channels=3, kernel_size=2, stride=1)

In [46]:
f

Conv2d(3, 2, kernel_size=(2, 2), stride=(1, 1))

In [48]:
## test pytorch example

In [49]:
f = nn.Conv2d(1, 6, 3)

In [51]:
x = torch.randn(1, 1, 32, 32)

In [53]:
f(x).shape

torch.Size([1, 6, 30, 30])