In [1]:
from __future__ import print_function

In [2]:
import torch

In [4]:
x = torch.empty(5,3)

In [3]:
torch.empty?

In [5]:
x

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [4.8788e-33, 3.8676e-43, 0.0000e+00],
        [0.0000e+00, 4.8788e-33, 3.8676e-43],
        [4.8783e-33, 3.8676e-43, 0.0000e+00]])

In [7]:
x = torch.rand(5,3)

In [8]:
x

tensor([[0.2440, 0.4537, 0.5828],
        [0.9577, 0.4327, 0.0492],
        [0.9831, 0.9775, 0.2726],
        [0.3595, 0.7498, 0.5282],
        [0.3618, 0.1141, 0.1881]])

In [9]:
x = torch.zeros(5, 3)

In [10]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
x = torch.tensor([5.5, 3])

In [11]:
torch.tensor?

In [14]:
x.dtype

torch.float32

In [15]:
x.shape

torch.Size([2])

In [17]:
x.size()

torch.Size([2])

In [18]:
x = x.new_ones(5, 3, dtype=torch.double) 

In [19]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [20]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.3237, 1.9981, 1.2040],
        [1.8801, 1.8626, 1.2916],
        [1.0471, 1.3297, 1.8320],
        [1.8142, 1.7096, 1.0077],
        [1.7583, 1.4643, 1.0647]], dtype=torch.float64)


In [21]:
y.add_(x)

tensor([[1.3237, 1.9981, 1.2040],
        [1.8801, 1.8626, 1.2916],
        [1.0471, 1.3297, 1.8320],
        [1.8142, 1.7096, 1.0077],
        [1.7583, 1.4643, 1.0647]])

In [22]:
y

tensor([[1.3237, 1.9981, 1.2040],
        [1.8801, 1.8626, 1.2916],
        [1.0471, 1.3297, 1.8320],
        [1.8142, 1.7096, 1.0077],
        [1.7583, 1.4643, 1.0647]])

In [23]:
y.add(x)

tensor([[2.3237, 2.9981, 2.2040],
        [2.8801, 2.8626, 2.2916],
        [2.0471, 2.3297, 2.8320],
        [2.8142, 2.7096, 2.0077],
        [2.7583, 2.4643, 2.0647]], dtype=torch.float64)

In [24]:
y

tensor([[1.3237, 1.9981, 1.2040],
        [1.8801, 1.8626, 1.2916],
        [1.0471, 1.3297, 1.8320],
        [1.8142, 1.7096, 1.0077],
        [1.7583, 1.4643, 1.0647]])

In [25]:
y.add_(x)

tensor([[2.3236, 2.9981, 2.2040],
        [2.8801, 2.8626, 2.2916],
        [2.0471, 2.3297, 2.8320],
        [2.8142, 2.7096, 2.0077],
        [2.7583, 2.4643, 2.0647]])

In [26]:
y

tensor([[2.3236, 2.9981, 2.2040],
        [2.8801, 2.8626, 2.2916],
        [2.0471, 2.3297, 2.8320],
        [2.8142, 2.7096, 2.0077],
        [2.7583, 2.4643, 2.0647]])

In [27]:
torch.cuda.is_available()

False